version: '3'
services:
  mysql:
    container_name: mysql
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=ROOT
    ports:
      - "3306:3306"
  nacos:
    image: nacos/nacos-server:v2.2.1-slim
    container_name: nacos
    restart: always
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - NACOS_AUTH_IDENTITY_KEY=2222
      - NACOS_AUTH_IDENTITY_VALUE=2xxx
      - NACOS_AUTH_TOKEN=SecretKey012345678901234567890123456789012345678901234567890123456789
    depends_on:
      - mysql
    ports:
      - "7848:7848"
      - "8848:8848"
      - "9848:9848"
  oap:
    image: apache/skywalking-oap-server:9.4.0
    container_name: oap
    restart: always
    ports:
      - "11800:11800"
      - "12800:12800"

  oap-ui:
    image: apache/skywalking-ui:9.4.0
    container_name: oap-ui
    restart: always
    environment:
      SW_OAP_ADDRESS: http://opa:12800
    ports:
      - "8080:8080"
    depends_on:
      - oap














